baseURL: https://lowpea.github.io
languageCode: en-us
theme: PaperMod
publishdir: docs

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics:

minify:
  disableXML: true

params:
  title: LowPea
  dateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  showReadingTime: true
  showToc: false
  showShareButtons: false
  showBreadCrumbs: false
  showPostNavLinks: true
  comments: false

  env: production
  author: Matthew W

  homeInfoParams:
    Title: Hi there, I'm Matthew.
    Content: >
      - University Student
      - <br>

    socialIcons:
      - name: github
        url: https://github.com/LowPea
    
    outputs:
      home:
        - HTML
        - RSS
        - JSON
      
      fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

        assets:
          disableHLJS: true
        
taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: monokai

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  expiryDate:
    - expiryDate
  lastmod:
    - :git
    - lastmod
    - date
    - publishDate
  publishDate:
    - publishDate
    - date

menu:
  main:
      - name: Archive
        url: archives
        weight: 1
      - name: Tags
        url: tags/
        weight: 3